name: Build Windows EXE
on: [push] # Собирать будет при каждом обновлении кода

jobs:
  build:
    runs-on: windows-latest # Запускаем на Windows сервере
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --windowed main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: dist/main.exe
